FROM openjdk:11

RUN apt update && apt install -y wget

WORKDIR /lavalink

RUN wget 'https://github.com/lavalink-devs/Lavalink/releases/download/4.0.5/Lavalink.jar'

COPY lavalink.yml application.yml
