FROM openjdk:11

RUN apt update && apt install -y wget

WORKDIR /lavalink

RUN wget 'https://github.com/lavalink-devs/Lavalink/releases/download/3.7.8/Lavalink.jar'

COPY lavalink.yml application.yml
