version: '3.8'

services:
  discord-bot:
    container_name: discord-bot
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - .:/app
    command: ["python3", "manage.py", "start"]
