# config for lavalink, put this file in the folder with Lavalink.jar
# this will then be renamed to application.yml inside the docker container running lavalink
server:
  port: 2333
  address: 0.0.0.0

spring:
  main:
    banner-mode: log

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    youtubeConfig:
      email: ""         # google account, gmail address
      password: ""      # google account, password
  httpConfig: 
    proxyHost: ""        # proxy, host ip
    proxyPort:           # proxy, host port
    proxyUser: ""        # proxy, username. if no authentication, leave empty
    proxyPassword: ""    # proxy, password. if no authentication, leave empty
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      snapshot: false
    # For more info: https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#plugin

plugins:
  youtube:
    enabled: true                 # Whether this source can be used.
    allowSearch: true             # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true     # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true  # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    # run `docker run quay.io/invidious/youtube-trusted-session-generator` to get the po_token
    pot:
      token: ""
      visitorData: ""
    clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5EMBEDDED

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO
