# config for lavalink, put this file in the folder with Lavalink.jar
server:
  port: 2333
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    youtubeConfig:
      email: ""         # google account, gmail address
      password: ""      # google account, password
  httpConfig: 
    proxyHost: ""        # proxy, host ip
    proxyPort:           # proxy, host port
    proxyUser: ""        # proxy, username. if no authentication, leave empty
    proxyPassword: ""    # proxy, password. if no authentication, leave empty
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      snapshot: false
    # For more info: https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#plugin
    # youtube:
    #   enabled: true
    #   allowSearch: true 
    #   allowDirectVideoIds: true
    #   allowDirectPlaylistIds: true
    #   clients:
    #     - MUSIC
    #     - ANDROID
    #     - WEB
    #   WEB: 
    #     playback: true
    #   TVHTML5EMBEDDED:
    #     playlistLoading: true
    #     videoLoading: true
    #     searching: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO
