import os
import sys
from loguru import logger
from pocketbase import PocketBase
from pocketbase.services.record_service import RecordService

POCKETBASE_URL: str = os.getenv("POCKETBASE_URL")
POCKETBASE_AUTH_EMAIL: str = os.getenv("POCKETBASE_AUTH_EMAIL")
POCKETBASE_AUTH_PASSWORD: str = os.getenv("POCKETBASE_AUTH_PASSWORD")
logger.debug(f"Using environment variables -> POCKETBASE_URL: {POCKETBASE_URL}, POCKETBASE_AUTH_EMAIL: {POCKETBASE_AUTH_EMAIL}, POCKETBASE_AUTH_PASSWORD: {POCKETBASE_AUTH_PASSWORD}")

try:
    conn = PocketBase(POCKETBASE_URL)
    logger.success("Connection to Pocketbase successful!")

    # Authentication
    user_data = conn.collection("nearbot_users").auth_with_password(
        POCKETBASE_AUTH_EMAIL, POCKETBASE_AUTH_PASSWORD
    )
    if not(user_data.is_valid):
        logger.error("Unable to authenticate with Pocketbase!")
        sys.exit()
    logger.success(f"Database authentication successful! Logged in as {user_data.record.id} ({user_data.record.name} - {user_data.record.email})")

except Exception as e:
    logger.error(f"Unable to connect to Pocketbase! {e}")
    sys.exit()

class Collections:
    def settings_embeds() -> RecordService:
        """
        Name: nearbot_settings_embeds
        System Fields (autogenerated):
            id:
                - Plain Text
                - Auto
            created
                - DateTime
                - Auto
            updated
                - DateTime
                - Auto
        User Fields:
            key
                - Plain Text
            value
                - Plain Text
        """
        return conn.collection("nearbot_settings_embeds")

    def commands_history() -> RecordService:
        """
        Name: nearbot_commands_history
        System Fields (autogenerated):
            id:
                - Plain Text
                - Auto
            created
                - DateTime
                - Auto
            updated
                - DateTime
                - Auto
        User Fields:
            command
                - Plain Text
            command_args
                - Plain Text
            author_id
                - Plain Text
            author_name
                - Plain Text
            server_id
                - Plain Text
            server_name
                - Plain Text
        """
        return conn.collection("nearbot_commands_history")
        