name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Logging into registry
        id: docker-login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Setting correct metadata for versioned tag
        id: docker-meta-1
        uses: docker/metadata-action@v5
        with:
          images: git.teamsds.net/TeamSDS/NearBot-Bot
          tags: type=semver,pattern={{version}}

      - name: Building and pushing image (versioned)
        id: docker-build-version
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta-1.outputs.tags }}
          labels: ${{ steps.docker-meta-1.outputs.labels }}

      - name: Setting correct metadata for latest tag
        id: docker-meta-2
        uses: docker/metadata-action@v5
        with:
          images: git.teamsds.net/TeamSDS/NearBot-Bot
          tags: type=raw,value=latest

      - name: Building and pushing image (latest)
        id: docker-build-latest
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta-2.outputs.tags }}
          labels: ${{ steps.docker-meta-2.outputs.labels }}
